import {
  BrainCircuit,
  Sparkles,
  Globe,
  Cloud,
  Container,
  Shield,
  Workflow,
  Zap,
  Smartphone,
  Palette,
  BarChart3,
  Brain,
  Lightbulb,
  Wrench,
  Building2,
  ShoppingCart,
  Users,
  UserCog,
  Contact,
  HeartPulse,
  Package,
  Calculator,
  Hospital,
  GraduationCap,
  Truck,
  Factory,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  brain_circuit: BrainCircuit,
  sparkles: Sparkles,
  globe: Globe,
  cloud: Cloud,
  container: Container,
  shield: Shield,
  workflow: Workflow,
  zap: Zap,
  smartphone: Smartphone,
  palette: Palette,
  bar_chart3: BarChart3,
  brain: Brain,
  lightbulb: Lightbulb,
  wrench: Wrench,
  building2: Building2,
  shopping_cart: ShoppingCart,
  users: Users,
  user_cog: UserCog,
  contact: Contact,
  heart_pulse: HeartPulse,
  package: Package,
  calculator: Calculator,
  hospital: Hospital,
  graduation_cap: GraduationCap,
  truck: Truck,
  factory: Factory,
};

export function getIcon(key: string): LucideIcon {
  return iconMap[key] ?? Building2;
}
